const { onExit } = require('@rafael-juliao/process-exit')
const dependencies = require('./Dependencies')
const application = dependencies.buildApplication()
application.start()
onExit(application.stop)