module.exports = {
    OFFER_CREATED: 'OFFER_CREATED',
    OFFER_UPDATED: 'OFFER_UPDATED',
    OFFER_STATUS_CHANGED: 'OFFER_STATUS_CHANGED',
    PRODUCT_CREATED: 'PRODUCT_CREATED',
    PRODUCT_UPDATED: 'PRODUCT_UPDATED',
    PRODUCT_STATUS_CHANGED: 'PRODUCT_STATUS_CHANGED',
}