version: '3'

networks: 
    app-network:
      driver: bridge
  
services:

  #############################################
  ## Message Broker: RabbitMQ
  #############################################
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
        # rabbit
        - 5672:5672
        # rabbit panel
        - 15672:15672
    volumes:
      - ./data/messages:/data/messages
    #environment:
    #  RABBITMQ_MNESIA_DIR: './data/messages'
    networks:
      - app-network

  #############################################
  ## Database: MongoDb
  #############################################
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  # Mongo admin at localhost:8081
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    networks:
      - app-network