version: '3'

services:

# RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    #environment:
    #    RABBITMQ_DEFAULT_USER: 'rabbit'
    #    RABBITMQ_DEFAULT_PASS: 'rabbit'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - app-network

# MongoDB
  mongodb:
    image: mongo
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - app-network

networks: 
    app-network:
      driver: bridge