version: '3'

networks: 
    app-network:
      driver: bridge

services:

# RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - app-network

# MongoDB
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

# micro-services
  offers-ms:
    image: node:13
    networks:
      - app-network
    volumes:
      - ../services/offers-ms:/usr/src/service
      - ./wait.sh:/usr/src/service/wait.sh
    working_dir: /usr/src/service
    depends_on:
      - "mongodb"
      - "rabbitmq"
    environment:
      MONGO_URL: 'mongodb'
      RABBIT_URL: 'rabbitmq'
    command: bash -c "./wait.sh mongodb:27017 && ./wait.sh rabbitmq:5672 && npm run app"
    ports:
      - 3000:3000