version: '3'

networks: 
    app-network:
      driver: bridge

services:

# RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    #environment:
    #    RABBITMQ_DEFAULT_USER: 'rabbit'
    #    RABBITMQ_DEFAULT_PASS: 'rabbit'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - app-network

# MongoDB
  mongodb:
    image: mongo
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - app-network


# Application
  application:
    image: node:13
    networks:
      - app-network
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service
    #command: bash -c "npm install && npm run app"
    depends_on:
      - "mongodb"
      - "rabbitmq"
    environment:
      MONGO_URL: 'mongodb'
      RABBIT_URL: 'rabbitmq'
    command: bash -c ".docker/wait.sh mongodb:27017 && .docker/wait.sh rabbitmq:5672 && npm run app"
    #command: [".docker/wait.sh", "mongodb:27017", "--", ".docker/wait.sh", "rabbitmq:5672", "--", "node index.js"]
    ports:
      - 3000:3000